# =============================================================================
# Resolve / persist Docker host workspace root (DBC_DOCKER_WORKSPACE)
# =============================================================================
# Priority:
#   1) -WorkspaceRoot argument
#   2) process env DBC_DOCKER_WORKSPACE
#   3) deploy/dbc-docker.env (persisted)
#   4) interactive prompt (only when -AllowPrompt)
#
# Dot-source then call:
#   . "$PSScriptRoot\Resolve-DbcDockerWorkspace.ps1"
#   $ws = Resolve-DbcDockerWorkspace -RepoRoot $RepoRoot -AllowPrompt
#
# Encoding: UTF-8 without BOM (required for Linux). Keep user-facing strings
# ASCII-only so Windows PowerShell 5.1 can parse this file without a BOM.
# =============================================================================

function ConvertTo-DbcDockerVolumePath {
    param([Parameter(Mandatory = $true)][string]$Path)
    $full = [System.IO.Path]::GetFullPath($Path.Trim().Trim('"').Trim("'"))
    return ($full -replace '\\', '/')
}

function ConvertTo-DbcHostPath {
    param([Parameter(Mandatory = $true)][string]$Path)
    $normalized = $Path.Trim().Trim('"').Trim("'") -replace '/', '\'
    return [System.IO.Path]::GetFullPath($normalized)
}

function Read-DbcDockerWorkspaceEnvFile {
    param([Parameter(Mandatory = $true)][string]$EnvFile)
    if (-not (Test-Path $EnvFile)) { return $null }
    foreach ($line in Get-Content -Path $EnvFile -ErrorAction SilentlyContinue) {
        if ($null -eq $line) { continue }
        $t = $line.Trim()
        if ($t -eq "" -or $t.StartsWith("#")) { continue }
        if ($t -match '^\s*DBC_DOCKER_WORKSPACE\s*=\s*(.+)\s*$') {
            return $Matches[1].Trim().Trim('"').Trim("'")
        }
    }
    return $null
}

function Save-DbcDockerWorkspaceEnvFile {
    param(
        [Parameter(Mandatory = $true)][string]$EnvFile,
        [Parameter(Mandatory = $true)][string]$DockerPath
    )
    $dir = Split-Path -Parent $EnvFile
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    $content = @(
        "# Auto-generated by scripts/Resolve-DbcDockerWorkspace.ps1 - do not commit.",
        "# Copy from deploy/dbc-docker.env.example if you edit manually.",
        "DBC_DOCKER_WORKSPACE=$DockerPath"
    ) -join "`r`n"
    Set-Content -Path $EnvFile -Value $content -Encoding ascii
}

function Resolve-DbcDockerWorkspace {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [string]$WorkspaceRoot = "",
        [switch]$AllowPrompt,
        [switch]$Quiet
    )

    $envFile = Join-Path $RepoRoot "deploy\dbc-docker.env"
    $raw = $null

    if (-not [string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
        $raw = $WorkspaceRoot
    } elseif (-not [string]::IsNullOrWhiteSpace($env:DBC_DOCKER_WORKSPACE)) {
        $raw = $env:DBC_DOCKER_WORKSPACE
    } else {
        $raw = Read-DbcDockerWorkspaceEnvFile -EnvFile $envFile
    }

    if ([string]::IsNullOrWhiteSpace($raw) -and $AllowPrompt) {
        $defaultHint = Join-Path $env:USERPROFILE "dbc-docker-data"
        Write-Host ""
        Write-Host "Docker data directory is not configured yet." -ForegroundColor Yellow
        Write-Host "  (Postgres / Redis / ES / secrets mounts live under this path.)"
        Write-Host "Enter any local path; it will be saved to deploy\dbc-docker.env."
        Write-Host "Or set env DBC_DOCKER_WORKSPACE / pass -WorkspaceRoot next time."
        Write-Host ""
        $inputPath = Read-Host "Host deploy path (Enter = $defaultHint)"
        if ([string]::IsNullOrWhiteSpace($inputPath)) {
            $raw = $defaultHint
        } else {
            $raw = $inputPath
        }
    }

    if ([string]::IsNullOrWhiteSpace($raw)) {
        throw @"
Docker data directory is not set. Use one of:
  1) .\scripts\docker-deploy.cmd -WorkspaceRoot D:\data\dbc
  2) `$env:DBC_DOCKER_WORKSPACE = 'D:\data\dbc'
  3) Copy deploy\dbc-docker.env.example to deploy\dbc-docker.env and set the path
"@
    }

    $hostPath = ConvertTo-DbcHostPath -Path $raw
    $dockerPath = ConvertTo-DbcDockerVolumePath -Path $hostPath

    Save-DbcDockerWorkspaceEnvFile -EnvFile $envFile -DockerPath $dockerPath
    $env:DBC_DOCKER_WORKSPACE = $dockerPath

    if (-not $Quiet) {
        Write-Host "Docker workspace: $hostPath"
        Write-Host "Persisted to:     $envFile (DBC_DOCKER_WORKSPACE=$dockerPath)"
    }

    return [pscustomobject]@{
        HostPath   = $hostPath
        DockerPath = $dockerPath
        EnvFile    = $envFile
    }
}